#!/usr/bin/env python

def options(opt):
  pass

def configure(conf):
  conf.check_cxx(lib = 'jubatus_classifier')

def build(bld):
  sources = ['classifier.cpp']
  headers = ['classifier.hpp']

  if bld.env.C_BINDING:
    sources += ['classifier_c.cpp']
    headers += ['classifier.h']

  bld.shlib(
    source = sources,
    target = 'jubatus_inprocess_classifier',
    use = ['JUBATUS', 'JUBATUS_DRIVER', 'JUBATUS_CLASSIFIER',
           'JUBASTORAGE', 'JUBACONVERTER', 'PFICOMMON'])

  bld.install_files('${INCLUDEDIR}/jubatus/inprocess/classifier', headers)
